routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('install', function () {
    \Illuminate\Support\Facades\Artisan::call('app:install');
    dd("app:install");
});
Route::get('update', function () {
    \Illuminate\Support\Facades\Artisan::call('app:update');
    dd("app:update");
});
Route::get('cache_clear', function () {
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    dd("cache:clear");
});
Route::get('config_clear', function () {
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    dd("config:clear");
});
Route::get('storage', function () {
    \Illuminate\Support\Facades\Artisan::call('storage:link');
    dd("storage");
});
Route::get('migrate', function () {
    \Illuminate\Support\Facades\Artisan::call('migrate');
    dd("migrate");
});
Route::get('seed', function () {
    \Illuminate\Support\Facades\Artisan::call('db:seed');
    dd("seed");
});
Route::get('up', function () {
    \Illuminate\Support\Facades\Artisan::call('up');
    dd("live");
});
Route::get('down', function () {
    \Illuminate\Support\Facades\Artisan::call('down');
    dd("maintenance");
});

Route::get('/', function () {
    return redirect(route('products.index'));
});
Route::get('/example_test', function () {
    return view('welcome');
});
Auth::routes([
    'register' => false
]);

Route::get('/home', function () {
    return redirect(route('products.index'));
})->name('home');
Route::get('storage/{path}', 'StorageController')->name('storage')->where('path', '[\-\/\w\.]+');
Route::resource('roles', 'RoleController');
Route::resource('transaction_statuses', 'TransactionStatusController');
Route::resource('product_categories', 'ProductCategoryController');
Route::get('products/adjust/{product}', 'ProductController@adjust')->name('products.adjust');
Route::resource('products', 'ProductController');
Route::resource('users', 'UserController');
Route::resource('transaction_ins', 'TransactionInController');
Route::resource('transaction_outs', 'TransactionOutController');
Route::get('stock_report', 'StockReportController')->name('stock_report');
Route::get('transaction_report', 'TransactionReportController')->name('transaction_report');
Route::post('institutions/cookie', 'InstitutionController@cookie')->name('institutions.cookie');
Route::resource('institutions', 'InstitutionController');
Route::get('notification', 'NotificationController')->name('notification');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\HtmlString;

/**
 * Product Model
 */
class Product extends BaseModel
{
    /** @var string Filter Class */
    protected $filters = 'App\Filters\ProductFilter';

    /** @var string $table */
    //protected $table = '';

    /** @var string $primaryKey */
    //protected $primaryKey = '';

    /** @var bool $incrementing */
    //public $incrementing = false;

    /** @var string $keyType */
    //protected $keyType = 'string';

    /** @var bool $timestamps */
    //public $timestamps = false;

    /** @var string $dateFormat */
    //protected $dateFormat = 'U';

    /** @var string CREATED_AT */
    //const CREATED_AT = '';
    /** @var string UPDATED_AT */
    //const UPDATED_AT = '';

    /** @var string $connection */
    //protected $connection = '';

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('global', function (Builder $query) {
            if (empty($query->getQuery()->columns))
                $query->select([
                    '*' => $query->qualifyColumn('*')
                ]);
        });

        static::addGlobalScope('by_user', function (Builder $query) {
            return $query->byUser();
        });
    }

    /**
     * @param Builder $query
     * @param User|null $user
     * @return \Illuminate\Database\Concerns\BuildsQueries|Builder|mixed
     */
    public function scopeByUser(Builder $query, User $user = null)
    {
        $user = $user ? : auth()->user();
        return $query->when($user instanceof User && $user->hasRole(['admin','staff']), function (Builder $query) use($user) {
            return $query->where($query->qualifyColumn('institution_id'), $user->institution_id);
        });
    }

    public function product_category()
    {
        return $this->belongsTo(ProductCategory::class);
    }

    public function getAbbreviationNameAttribute()
    {
        $name_array = explode(" ", $this->name);
        $abb = array_map(function ($name) {
            return str_split($name)[0];
        }, $name_array);
        array_shift($abb);
        return $name_array[0].' '.implode('', $abb);
    }

    public function getPictureHtmlAttribute()
    {
        return $this->picture? new HtmlString("<img src='/storage/$this->picture' alt='transaction-picture' style='width: 200px; height: auto;'>"): '';
    }
}

app/Transaction.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\HtmlString;

/**
 * Transaction Model
 */
class Transaction extends BaseModel
{
    /** @var string Filter Class */
    protected $filters = 'App\Filters\TransactionFilter';

    /** @var string $table */
    //protected $table = '';

    /** @var string $primaryKey */
    //protected $primaryKey = '';

    /** @var bool $incrementing */
    //public $incrementing = false;

    /** @var string $keyType */
    //protected $keyType = 'string';

    /** @var bool $timestamps */
    //public $timestamps = false;

    /** @var string $dateFormat */
    //protected $dateFormat = 'U';

    /** @var string CREATED_AT */
    //const CREATED_AT = '';
    /** @var string UPDATED_AT */
    //const UPDATED_AT = '';

    /** @var string $connection */
    //protected $connection = '';

    // TODO: Define other default value and relations

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('by_user', function (Builder $query) {
            return $query->byUser();
        });
    }

    /**
     * @param Builder $query
     * @param User|null $user
     * @return \Illuminate\Database\Concerns\BuildsQueries|Builder|mixed
     */
    public function scopeByUser(Builder $query, User $user = null)
    {
        $user = $user ? : auth()->user();
        return $query->when($user instanceof User && $user->hasRole(['admin','staff']), function (Builder $query) use($user) {
            return $query->where($query->qualifyColumn('institution_id'), $user->institution_id);
        });
    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function transaction_status()
    {
        return $this->belongsTo(TransactionStatus::class);
    }

    public function getCreatedAtForHumanAttribute()
    {
        return date('d M Y H:i', strtotime($this->created_at));
    }

    public function getCreatedDateMonthAttribute()
    {
        return date('d M', strtotime($this->created_at));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="ibox float-e-margins">
            <div class="ibox-title"><h5>Dashboard</h5>
              <div class="ibox-tools"> <span class="label label-warning-light pull-right">Welcome</span></div>
            </div>

            <div class="ibox-content">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif

                You are logged in!
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/notification.blade.php
@extends('layouts.app')

@section('content-title', ucwords(__('notification.plural')))

@section('content')
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    @component(config('generator.view_component').'components.panel')
      @slot('title')
        Semua Notifikasi
      @endslot

      @if (session('status'))
      <div class="alert alert-success">
        {{ session('status') }}
      </div>
      @endif
      <div class="table-responsive">
          <table id="products" class="table table-striped table-hover table-condensed table-sm">
              <thead class="text-nowrap">
              <tr>
                  <th width="1px" class="text-center">No</th>
                  <th class="text-center">Kategori</th>
                  <th class="text-center">Nama</th>
                  <th class="text-center">Stok</th>
                  <th class="text-center">Keterangan</th>
                  <th></th>
              </tr>
              </thead>
              <tbody>
              @foreach($products as $key => $product)
                  <tr>
                      <td class="text-right">{{ $key+1 }}</td>
                      <td>{{ $product->product_category->name }}</td>
                      <td>{{ $product->name }}</td>
                      <td>{{ $product->stock }}</td>
                      <td>{{ $product->noted }}</td>
                      <td class="action text-nowrap text-right">
                          <a href="{{ route('products.show', [$product]) }}" class="btn btn-success btn-sm btn-xs">Detail</a>
                      </td>
                  </tr>
              @endforeach
              </tbody>
          </table>
      </div>
    @endcomponent
  </div>
</div>
@endsection

resources/views/stock_report.blade.php
@extends('layouts.app')

@section('content-title', ucwords(__('stock_report.plural')))

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Grafik Stok Barang</h5>
                </div>
                <div class="ibox-content">
                    @if($products->count())
                    <div>
                        <canvas id="barChart" height="90"></canvas>
                    </div>
                    <div class="row m-t-sm">
                        <div class="col-md-8 col-md-offset-2">
                            <h5>Keterangan:</h5>
                            <table class="table table-borderless">
                                @foreach($products as $key => $product)
                                    @if($key%2==0)
                                        <tr>
                                            <td>{{ $product->abbreviation_name }}</td>
                                            <td>:</td>
                                            <td>{{ $product->name }}</td>
                                    @else
                                            <td class="text-right">{{ $product->abbreviation_name }}</td>
                                            <td>:</td>
                                            <td>{{ $product->name }}</td>
                                        </tr>
                                    @endif
                                @endforeach
                                @if(($products->count())%2==1)
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    </tr>
                                @endif
                            </table>
                        </div>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        @component(config('generator.view_component').'components.panel')
          @slot('title')
            {{ ucwords(__('stock_report.plural')) }}
          @endslot
          @slot('tools')
              <div class="ibox-tools">
                  <a href="{{ route('stock_report', ['pdf']) }}" class="btn btn-primary btn-sm">
                      <i class="fa fa-print"></i> Cetak Laporan
                  </a>
              </div>
          @endslot
            @if (session('status'))
              <div class="alert alert-success">
                {{ session('status') }}
              </div>
            @endif
          <div class="table-responsive">
              <table id="products" class="table table-striped table-hover table-condensed table-sm">
                  <thead class="text-nowrap">
                  <tr>
                      <th width="1px" class="text-center">No</th>
                      <th class="text-center">Kategori</th>
                      <th class="text-center">
                          Nama
                          <a href="http://instock.test/products?sort=name%2Cdesc">
                              <i class="fa fa-sort text-muted"></i>
                          </a>
                      </th>
                      <th class="text-center">Stok</th>
                      <th class="text-center">Keterangan</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                      <td></td>
                      <td></td>
                      <td>
                          <input name="name" value="" placeholder="Semua" form="search" class="form-control">
                      </td>
                      <td></td>
                      <td></td>
                  </tr>
                  @foreach($products as $key => $product)
                  <tr>
                      <td class="text-right">{{ $key+1 }}</td>
                      <td>
                          <a href="http://instock.test/product_categories/2?redirect=http%3A%2F%2Finstock.test%2Fproducts">
                              {{ $product->product_category->name }}
                          </a>
                      </td>
                      <td>{{ $product->name }}</td>
                      <td>{{ $product->stock }}</td>
                      <td>{{ $product->noted }}</td>
                  </tr>
                  @endforeach
                  </tbody>
              </table>
          </div>
        @endcomponent
      </div>
    </div>
@endsection
@push('body')
    <!-- ChartJS-->
    <script src="/js/plugins/chartJs/Chart.min.js"></script>
    @if($products->count())
        @php
            /** @var \App\Product $products */
            $labels = $products->map(function ($product) {
                return $product->abbreviation_name;
            });
            $labels_name = $products->map(function ($product) {
                return $product->name;
            });
            $value = $products->map(function ($product) {
                return $product->stock;
            });
        @endphp
        <script>
            $(function () {
                let barData = {
                    labels: @json($labels),
                    labels_name: @json($labels_name),
                    datasets: [
                        {
                            label: "Barang",
                            backgroundColor: 'rgba(26,179,148,0.5)',
                            borderColor: "rgba(26,179,148,0.7)",
                            pointBackgroundColor: "rgba(26,179,148,1)",
                            pointBorderColor: "#fff",
                            data: @json($value),
                        }
                    ]
                };

                let barOptions = {
                    responsive: true,
                    tooltips: {
                        callbacks: {
                            title: function (tooltipItem, data) {
                                return data.labels_name[tooltipItem[0].index];
                            },
                            label: function (tooltipItem, data) {
                                return 'Tersisa: '+Math.round(data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index]);
                            }
                        }
                    }
                };

                var ctx2 = document.getElementById("barChart").getContext("2d");
                new Chart(ctx2, {type: 'horizontalBar', data: barData, options:barOptions});
            });
        </script>
    @endif
@endpush

resources/views/transaction_report.blade.php
@extends('layouts.app')

@section('content-title', ucwords(__('transaction_report.plural')))

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Grafik Transaksi</h5>
                </div>
                <div class="ibox-content">
                    <div>
                        <canvas id="lineChart" height="80"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        @component(config('generator.view_component').'components.panel')
          @slot('title')
            {{ ucwords(__('transaction_report.plural')) }}
          @endslot
          @slot('tools')
              <div class="ibox-tools">
                  <a href="{{ route('transaction_report', ['pdf']) }}" class="btn btn-primary btn-sm">
                      <i class="fa fa-print"></i> Cetak Laporan
                  </a>
              </div>
          @endslot

          @if (session('status'))
          <div class="alert alert-success">
            {{ session('status') }}
          </div>
          @endif
              <form id="search" method="GET" class="form">
                  <div class="row" style="margin-bottom: 15px;">
                      <div class="col-xs-6 col-6 col-md-4">
                          <div class="input-group">
                              <span class="input-group-btn input-group-prepend">
                                  <button type="submit" class="btn btn-default btn-secondary btn-sm">&nbsp;<i class="fa fa-search"></i>&nbsp;</button>
                              </span>
                              <input type="text" name="search" placeholder="Cari" value="" autofocus="autofocus" class="input-sm form-control form-control-sm">
                          </div>
                      </div>
                      <div class="col-xs-6 col-6 col-md-8">
                          <div class="text-right">
                              <span>1 - 2 dari 2</span>&nbsp;
                              <div style="display: inline-block;">
                                  <select name="per_page" id="per_page" onchange="this.form.submit()" title="per page" class="form-control form-control-sm input-sm">
                                      <option value="15">15</option>
                                      <option value="50">50</option>
                                      <option value="100">100</option>
                                      <option value="250">250</option>
                                  </select>
                              </div>
                          </div>
                      </div>
                  </div>
              </form>
              <div class="table-responsive">
                  <table id="transactions" class="table table-striped table-hover table-condensed table-sm">
                      <thead class="text-nowrap">
                      <tr>
                          <th width="1px" class="text-center">No</th>
                          <th class="text-center">Tanggal Transaksi</th>
                          <th class="text-center">Produk</th>
                          <th class="text-center" style="width: 85px;">Tipe</th>
                          <th class="text-center">Status</th>
                          <th class="text-center">User</th>
                          <th class="text-center">Petugas Lapangan</th>
                          <th class="text-center">Jumlah</th>
                          <th class="text-center">Keterangan</th>
                      </tr>
                      </thead>
                      <tbody>
                      <tr>
                          <td></td>
                          <td></td>
                          <td>
                              <select2-ajax
                                  class="form-control"
                                  name="product_id"
                                  form="search"
                                  onchange="this.form.submit()"
                                  url="/api/products"
                                  :params="{institution_id: {{request()->cookie('institution_id')}} }"
                                  text-property="name"
                                  value="{{ request()->query('product_id') }}"
                                  placeholder="{{ __('All') }}"
                              >
                              </select2-ajax>
                          </td>
                          <td>
                              <select name="in_out" id="in_out" form="search" onchange="this.form.submit()" title="type" class="form-control">
                                  <option value="">All</option>
                                  <option value="in" {{request()->in_out=='in'?'selected':''}}>Masuk</option>
                                  <option value="out" {{request()->in_out=='out'?'selected':''}}>Keluar</option>
                              </select>
                          </td>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                          <td></td>
                      </tr>
                      @foreach($transactions as $key => $transaction)
                      <tr>
                          <td class="text-right">{{$key+1}}</td>
                          <td>{{ $transaction->created_at_for_human }}</td>
                          <td>{{ $transaction->product->name }}</td>
                          <td>
                              @if($transaction->in_out=='in')
                                  <span class="bg-info" style="padding: 2px 5px; border-radius: 3px"><i class="fa fa-download"></i> Masuk</span>
                              @else
                                  <span class="bg-danger" style="padding: 2px 5px; border-radius: 3px"><i class="fa fa-upload"></i> Keluar</span>
                              @endif
                          </td>
                          <td>{{ $transaction->transaction_status->name }}</td>
                          <td>{{ $transaction->user->name }}</td>
                          <td>{{ $transaction->officer }}</td>
                          <td>{{ $transaction->amount }}</td>
                          <td>{{ $transaction->noted }}</td>
                      </tr>
                      @endforeach
                      </tbody>
                  </table>
              </div>
        @endcomponent
      </div>
    </div>
@endsection
@push('body')
    <!-- ChartJS-->
    <script src="js/plugins/chartJs/Chart.min.js"></script>
{{--    <script src="js/demo/chartjs-demo.js"></script>--}}
    @php
        $indo_month = ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
        /** @var \App\Transaction $transactions */
        $labels = $transactions->map(function ($transaction) use ($indo_month) {
            return $transaction->created_at->format('j').' '.$indo_month[$transaction->created_at->format('n')-1];
        });
        $transaction_in = $transactions->map(function ($transaction) {
            return $transaction->in_out=='in'?$transaction->amount:'0';
        });
        $transaction_out = $transactions->map(function ($transaction) {
            return $transaction->in_out=='out'?$transaction->amount:'0';
        });
        $stock= [];
        if (request()->product_id) {
            $temp = 0;
            foreach ($transactions as $key => $transaction) {
                if ($transaction->in_out=='in') {
                    $temp += $transaction->amount;
                } else {
                    $temp -= $transaction->amount;
                }
                array_push($stock, $temp);
            }
        }
    @endphp
    <script>
        $(function () {
            let lineData = {
                labels: @json($labels),
                datasets: [
                    {
                        label: "Stok",
                        backgroundColor: 'transparent',
                        borderColor: "rgba(155,201,196,0.7)",
                        pointBackgroundColor: "rgb(145,173,170)",
                        pointBorderColor: "#fff",
                        data: @json($stock)
                    },
                    {
                        label: "Trx Masuk",
                        backgroundColor: 'transparent',
                        borderColor: "rgba(26,179,148,0.7)",
                        pointBackgroundColor: "rgba(26,179,148,1)",
                        pointBorderColor: "#fff",
                        data: @json($transaction_in)
                    },
                    {
                        label: "Trx Keluar",
                        backgroundColor: 'transparent',
                        borderColor: "rgb(165,54,54)",
                        pointBackgroundColor: "rgb(179,26,26)",
                        pointBorderColor: "#fff",
                        data: @json($transaction_out)
                    },
                ]
            }
            let lineOptions = {
                responsive: true
            };
            let ctx = document.getElementById("lineChart").getContext("2d");
            new Chart(ctx, {type: 'line', data: lineData, options:lineOptions});
        });
    </script>
@endpush